"""empty message

Revision ID: b7b23d20292a
Revises: 7bdd80fba70d
Create Date: 2020-08-03 19:58:59.022141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b23d20292a'
down_revision = '7bdd80fba70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('events', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'end_date')
    op.drop_table('event')
    # ### end Alembic commands ###
